/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './consumo';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/dweet-service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import22 from 'ionic-angular/config/config';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from 'ionic-angular/navigation/view-controller';
import * as import25 from 'ionic-angular/components/app/app';
import * as import26 from 'ionic-angular/components/menu/menu-controller';
import * as import27 from 'ionic-angular/components/toolbar/toolbar';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from '@angular/core/src/linker/template_ref';
import * as import32 from 'ionic-angular/components/icon/icon';
import * as import33 from 'ionic-angular/components/button/button';
import * as import34 from 'ionic-angular/components/menu/menu-toggle';
import * as import35 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import36 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import37 from 'ionic-angular/components/navbar/navbar';
import * as import38 from '@angular/common/src/directives/ng_if';
import * as import39 from 'ionic-angular/components/content/content';
import * as import40 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import41 from 'angular2-highcharts/dist/HighchartsService';
import * as import42 from '../../node_modules/angular2-highcharts/dist/ChartComponent.ngfactory';
import * as import43 from 'ionic-angular/components/card/card';
import * as import44 from 'angular2-highcharts/dist/ChartComponent';
export class Wrapper_ConsumoPage {
  context:import0.ConsumoPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.ConsumoPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_ConsumoPage_Host:import2.RenderComponentType = (null as any);
class _View_ConsumoPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ConsumoPage_0_4:Wrapper_ConsumoPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumoPage_Host0,renderType_ConsumoPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-consumo',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ConsumoPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ConsumoPage_0_4 = new Wrapper_ConsumoPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.DweetService));
    this._appEl_0.initComponent(this._ConsumoPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ConsumoPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ConsumoPage) && (0 === requestNodeIndex))) { return this._ConsumoPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ConsumoPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._ConsumoPage_0_4.context.ngOnDestroy();
  }
}
function viewFactory_ConsumoPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ConsumoPage_Host === (null as any))) { (renderType_ConsumoPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ConsumoPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ConsumoPageNgFactory:import11.ComponentFactory<import0.ConsumoPage> = new import11.ComponentFactory<import0.ConsumoPage>('page-consumo',viewFactory_ConsumoPage_Host0,import0.ConsumoPage);
const styles_ConsumoPage:any[] = ([] as any[]);
var renderType_ConsumoPage:import2.RenderComponentType = (null as any);
class _View_ConsumoPage0 extends import1.AppView<import0.ConsumoPage> {
  _el_0:any;
  _Header_0_3:import12.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import13.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _Button_4_4:import14.Wrapper_Button;
  _MenuToggle_4_5:import15.Wrapper_MenuToggle;
  _ToolbarItem_4_6:import16.Wrapper_ToolbarItem;
  _query_Button_4_0:import17.QueryList<any>;
  _text_5:any;
  _el_6:any;
  _Icon_6_3:import18.Wrapper_Icon;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _ToolbarTitle_9_4:import19.Wrapper_ToolbarTitle;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _Content_14_4:import20.Wrapper_Content;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import21.Wrapper_NgIf;
  _text_17:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumoPage0,renderType_ConsumoPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Wrapper_Header(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import24.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import25.App),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'ion-button','');
    this.renderer.setElementAttribute(this._el_4,'menuToggle','');
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import14.viewFactory_Button0(this.viewUtils,this.injector(4),this._appEl_4);
    this._Button_4_4 = new import14.Wrapper_Button('','',this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer);
    this._MenuToggle_4_5 = new import15.Wrapper_MenuToggle(this.parentInjector.get(import26.MenuController),new import23.ElementRef(this._el_4),this.parentInjector.get(import24.ViewController,(null as any)),this._Navbar_2_4.context);
    this._ToolbarItem_4_6 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import27.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._query_Button_4_0 = new import17.QueryList<any>();
    this._appEl_4.initComponent(this._Button_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_6 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_6,'name','menu');
    this.renderer.setElementAttribute(this._el_6,'role','img');
    this._Icon_6_3 = new import18.Wrapper_Icon(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_4.create(this._Button_4_4.context,[([] as any[]).concat([
        this._text_5,
        this._el_6,
        this._text_7
      ]
    )],(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_9 = new import3.AppElement(9,2,this,this._el_9);
    var compView_9:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(9),this._appEl_9);
    this._ToolbarTitle_9_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import27.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_9.initComponent(this._ToolbarTitle_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'Consumo',(null as any));
    compView_9.create(this._ToolbarTitle_9_4.context,[([] as any[]).concat([this._text_10])],(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11
      ]
      )
    ]
    ,(null as any));
    this._text_12 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_14,'padding','');
    this._appEl_14 = new import3.AppElement(14,(null as any),this,this._el_14);
    var compView_14:any = import20.viewFactory_Content0(this.viewUtils,this.injector(14),this._appEl_14);
    this._Content_14_4 = new import20.Wrapper_Content(this.parentInjector.get(import22.Config),new import23.ElementRef(this._el_14),this.renderer,this.parentInjector.get(import25.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import24.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_14.initComponent(this._Content_14_4.context,([] as any[]),compView_14);
    this._text_15 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_16 = new import3.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import31.TemplateRef_(this._appEl_16,viewFactory_ConsumoPage1);
    this._NgIf_16_6 = new import21.Wrapper_NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText((null as any),'\n',(null as any));
    compView_14.create(this._Content_14_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_15,
        this._appEl_16,
        this._text_17
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_4,'click',this.eventHandler(this._handle_click_4_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.Icon) && (6 === requestNodeIndex))) { return this._Icon_6_3.context; }
    if (((token === import33.Button) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Button_4_4.context; }
    if (((token === import34.MenuToggle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._MenuToggle_4_5.context; }
    if (((token === import35.ToolbarItem) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ToolbarItem_4_6.context; }
    if (((token === import36.ToolbarTitle) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._ToolbarTitle_9_4.context; }
    if (((token === import37.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Navbar_2_4.context; }
    if (((token === import27.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Header_0_3.context; }
    if (((token === import31.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import38.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import39.Content) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Content_14_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._Button_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    const currVal_3:any = '';
    this._MenuToggle_4_5.check_menuToggle(currVal_3,throwOnChange,false);
    this._MenuToggle_4_5.detectChangesInternal(this,this._el_4,throwOnChange);
    this._ToolbarItem_4_6.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_5:any = 'menu';
    this._Icon_6_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_6_3.detectChangesInternal(this,this._el_6,throwOnChange);
    if (this._ToolbarTitle_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    if (this._Content_14_4.detectChangesInternal(this,this._el_14,throwOnChange)) { this._appEl_14.componentView.markAsCheckOnce(); }
    const currVal_8:boolean = !this.context.isLoading;
    this._NgIf_16_6.check_ngIf(currVal_8,throwOnChange,false);
    this._NgIf_16_6.detectChangesInternal(this,this._anchor_16,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_4_0.dirty) {
        this._query_Button_4_0.reset([this._Button_4_4.context]);
        this._ToolbarItem_4_6.context._buttons = this._query_Button_4_0;
        this._query_Button_4_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_4_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_4:any = this._MenuToggle_4_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'hidden',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_6_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_6,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._Content_14_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_14,'statusbar-padding',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_6_3.context.ngOnDestroy();
    this._Content_14_4.context.ngOnDestroy();
  }
  private _handle_click_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_4_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ConsumoPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ConsumoPage> {
  if ((renderType_ConsumoPage === (null as any))) { (renderType_ConsumoPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_ConsumoPage,{})); }
  return new _View_ConsumoPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ConsumoPage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Card_2_3:import40.Wrapper_Card;
  _text_3:any;
  _el_4:any;
  _CardContent_4_3:import40.Wrapper_CardContent;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _Icon_12_3:import18.Wrapper_Icon;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import18.Wrapper_Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _HighchartsService_21_4:import41.HighchartsService;
  _ChartComponent_21_5:import42.Wrapper_ChartComponent;
  _query_ChartSeriesComponent_21_0:import17.QueryList<any>;
  _query_ChartXAxisComponent_21_1:import17.QueryList<any>;
  _query_ChartYAxisComponent_21_2:import17.QueryList<any>;
  _text_22:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ConsumoPage1,renderType_ConsumoPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-card',(null as any));
    this._Card_2_3 = new import40.Wrapper_Card(this.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_4,'style','text-align: center; font-size: 5rem;');
    this._CardContent_4_3 = new import40.Wrapper_CardContent();
    this._text_5 = this.renderer.createText(this._el_4,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'style','text-align: center;');
    this._text_9 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_12,'color','primary');
    this.renderer.setElementAttribute(this._el_12,'name','md-calendar');
    this.renderer.setElementAttribute(this._el_12,'role','img');
    this._Icon_12_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText(this._el_10,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_8,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'color','secondary');
    this.renderer.setElementAttribute(this._el_17,'name','md-time');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import22.Config),new import23.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText(this._el_15,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_8,'\n    ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'chart',(null as any));
    this.renderer.setElementAttribute(this._el_21,'style','display : block;');
    this._appEl_21 = new import3.AppElement(21,0,this,this._el_21);
    var compView_21:any = import42.viewFactory_ChartComponent0(this.viewUtils,this.injector(21),this._appEl_21);
    this._HighchartsService_21_4 = new import41.HighchartsService();
    this._ChartComponent_21_5 = new import42.Wrapper_ChartComponent(new import23.ElementRef(this._el_21),this._HighchartsService_21_4);
    this._query_ChartSeriesComponent_21_0 = new import17.QueryList<any>();
    this._query_ChartXAxisComponent_21_1 = new import17.QueryList<any>();
    this._query_ChartYAxisComponent_21_2 = new import17.QueryList<any>();
    this._appEl_21.initComponent(this._ChartComponent_21_5.context,([] as any[]),compView_21);
    this._query_ChartSeriesComponent_21_0.reset(([] as any[]));
    this._ChartComponent_21_5.context.series = this._query_ChartSeriesComponent_21_0.first;
    this._query_ChartXAxisComponent_21_1.reset(([] as any[]));
    this._ChartComponent_21_5.context.xAxis = this._query_ChartXAxisComponent_21_1.first;
    this._query_ChartYAxisComponent_21_2.reset(([] as any[]));
    this._ChartComponent_21_5.context.yAxis = this._query_ChartYAxisComponent_21_2.first;
    compView_21.create(this._ChartComponent_21_5.context,([] as any[]),(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_21,'load',this.eventHandler(this._handle_load_21_0.bind(this)));
    const subscription_0:any = this._ChartComponent_21_5.context.load.subscribe(this.eventHandler(this._handle_load_21_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import43.CardContent) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._CardContent_4_3.context; }
    if (((token === import43.Card) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Card_2_3.context; }
    if (((token === import32.Icon) && (12 === requestNodeIndex))) { return this._Icon_12_3.context; }
    if (((token === import32.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3.context; }
    if (((token === import41.HighchartsService) && (21 === requestNodeIndex))) { return this._HighchartsService_21_4; }
    if (((token === import44.ChartComponent) && (21 === requestNodeIndex))) { return this._ChartComponent_21_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Card_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._CardContent_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_1:any = 'primary';
    this._Icon_12_3.check_color(currVal_1,throwOnChange,false);
    const currVal_2:any = 'md-calendar';
    this._Icon_12_3.check_name(currVal_2,throwOnChange,false);
    this._Icon_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    const currVal_5:any = 'secondary';
    this._Icon_17_3.check_color(currVal_5,throwOnChange,false);
    const currVal_6:any = 'md-time';
    this._Icon_17_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    const currVal_10:any = this.parent.context.options;
    this._ChartComponent_21_5.check_options(currVal_10,throwOnChange,false);
    this._ChartComponent_21_5.detectChangesInternal(this,this._el_21,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'\n        ',this.parent.context.dweet.with_[0].content.consumo,' W\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_5,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._Icon_12_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_12,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'\n        ',this.parent.context.dweet.with_[0].date,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_13,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._Icon_17_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = import4.interpolate(1,'\n        ',this.parent.context.dweet.with_[0].time,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_18,currVal_8);
      this._expr_8 = currVal_8;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._ChartComponent_21_5.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_12_3.context.ngOnDestroy();
    this._Icon_17_3.context.ngOnDestroy();
  }
  private _handle_load_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.saveInstance($event.context)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ConsumoPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ConsumoPage1(viewUtils,parentInjector,declarationEl);
}